name: Auto-build

on: [push, pull_request, workflow_dispatch]

jobs:        
  msvc:
    name: Build with MSVC
    runs-on: windows-latest
    strategy:
        matrix:
            build_type: ["Release", "Debug"]
    steps:
    - uses: actions/checkout@v3
    - name: Compile with MSVC for Windows
      run: |
        cmake -A Win32 . -B build_msvc
        cmake --build build_msvc --config ${{ matrix.build_type }}
      shell: bash
    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSVC_DLL_${{ matrix.build_type }}
        path: |
          ${{ github.workspace }}/build_msvc/MTA-package/${{ matrix.build_type }}/ml_package.dll
          